apps/users/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$',views.login, name='login'),
    url(r'^login/$',views.login, name='login'),
    url(r'^register/$',views.register, name='register'),
    url(r'^process_register/$',views.process_register, name='process_register'),
    url(r'^process_login/$',views.process_login, name='process_login'),
    url(r'^logged_in/$',views.logged_in, name='logged_in'),
]

belt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.users.urls', namespace='users')),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^admin/', admin.site.urls),
]

apps/users/models.py
from django.db import models
import re
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
import bcrypt

# Create your models here.
class UserManager(models.Manager):
    def validate(self, form):
        errors = []
        try:
            user = self.get(email=form['email'])
            if not bcrypt.checkpw(form['password'].encode(), user.password.encode()):
                errors.append("Email or password is bad")
        except:
            errors.append('Email or password is bad')
        if len(errors)>0:
            return False
        else:
            return True

    def register_validate(self, form):
        errors = []
        if len(form['f_name'])<2:
            errors.append('First name is to short.')
        if len(form['l_name'])<2:
            errors.append('Last name is to short.')
        if len(form['password'])<2:
            errors.append('Password is to short.')

        if not EMAIL_REGEX.match(form['email']):
            errors.append('Email must be valid')
        email_list = self.filter(email=form['email'])
        if len(email_list) > 0:
            errors.append('Email already in use')

        if form['password'] != form['confirm_password']:
            errors.append('Password must match the Confirm password')
        return errors


    def create_user(self, form):
        pw_hash = bcrypt.hashpw(form['password'].encode(), bcrypt.gensalt())
        user = self.create(
            f_name=form['f_name'],
            l_name=form['l_name'],
            email=form['email'],
            password=pw_hash,
        )
        return user


class User(models.Model):
    f_name = models.CharField(max_length=255)
    l_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User

# Create your views here.
def login(request):
    return render(request, 'users/loginbase_login.html')

def register(request):
    return render(request, 'users/loginbase_register.html')

def logged_in(request):
    print(request.POST)
    print('in logged_in')
    if 'user_id' not in request.session:
        return redirect('/login')
    name = User.objects.get(id=request.session['user_id'])
    context = {
        'name':name.f_name
    }
    return render(request, 'users/logged_in.html', context)

def process_login(request):
    print(request.POST)
    if User.objects.validate(request.POST):
        user = User.objects.get(email=request.POST['email'])
        print(user.f_name)
        print('8'*80)
        request.session['user_id'] = user.id
    else:
        error = 'Email or password is incorrect, please verify or register.'
        messages.error(request, error)
        return redirect('/login')
    return redirect('/users/logged_in')

def process_register(request):
    errors = User.objects.register_validate(request.POST)

    if errors:
        for error in errors:
            messages.error(request, error)
    else:
        user =User.objects.create_user(request.POST)
        print(user.f_name)
        print('8'*80)
        request.session['user_id'] = user.id
        return redirect('/users/logged_in')

    return redirect('/register')


def logout(request):
    pass

apps/users/templates/users/logged_in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load static %}
    <!--<link rel="stylesheet" type="text/css" href="main.css"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'main/main.css' %}">
</head>
<body>
<div class="container">

{{ name }} is logged in.
</div>
</body>
</html>

apps/users/templates/users/loginbase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    {% load static %}
    <!--<link rel="stylesheet" type="text/css" href="main.css"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'users/main.css' %}">
</head>
<body>
<div class="container">

        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'users:logged_in' %}">User Home</a>
                </div>
                <ul class="nav navbar-nav">
                    <li><a href="#">Recent Books</a></li>
                    <li><a href="{% url 'users:logged_in' %}">User Home</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'users:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                </ul>
            </div>
        </nav>

    {% block content %}
    {% endblock %}
</div>
</body>
</html>

apps/users/templates/users/loginbase_login.html
{% extends 'users/loginbase.html' %}

{% block content %}

    <div class="container">
        <h1>login page</h1>
        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
        <form action="/process_login/" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="text" class="form-control" name="email">
            </div>
            <div class="form-group">
                <label form="text">Password:</label>
                <input type="password" class="form-control" name="password">
            </div>
            <div class="form-group">
                <input type="submit" value="Submit">
            </div>
        </form>
        <a href="/users/register/">Register new user</a>
    </div>
{% endblock %}

apps/users/templates/users/loginbase_register.html
{% extends 'users/loginbase.html' %}

{% block content %}

    <h1>register</h1>
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    <form action="/process_register/" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="f_name">First Name:</label>
            <input type="text" class="form-control" name="f_name">
        </div>
        <div class="form-group">
            <label for="l_name">Last Name:</label>
            <input type="text" class="form-control" name="l_name">
        </div>
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="text" class="form-control" name="email">
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" class="form-control" name="password">
        </div>
        <div class="form-group">
            <label for="confirm_password">Confirm Password:</label>
            <input type="password" class="form-control" name="confirm_password">
        </div>
        <div class="form-group">
            <input type="submit" value="Submit">
        </div>
    </form>
    <a href="/users/login/">Login Page</a>
</div>
{% endblock %}